name: Issue to Post

on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - reopened

jobs:
  create_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create post file
        run: |
          echo "title: ${{ github.event.issue.title }}" >> post.md
          echo "body: ${{ github.event.issue.body }}" >> post.md
      - name: Commit and push changes
        run: |
          git add post.md
          git commit -m "Create post for issue #${{ github.event.issue.number }}"
          git push
