name: Issue to Post

on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - edited

jobs:
  create_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create post file
        run: |
          FILENAME="_posts/$(date +%Y-%m-%d)-$(echo -n ${{ github.event.issue.title }}) | tr '[A-Z]' '[a-z]' | tr -c 'a-z' '-' }}.md"
          echo --- > $FILENAME
          echo title: ${{ github.event.issue.title }} >> $FILENAME
          echo layout: post >> $FILENAME
          echo date: $(date +"%Y-%m-%d %H:%M %z") >> $FILENAME
          echo --- >> $FILENAME
          echo >> $FILENAME
          echo "${{ github.event.issue.body }}" >> $FILENAME
      - name: Commit and push changes
        run: |
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add .
          git commit -m "Create post for issue #${{ github.event.issue.number }}"
          git push
